### PR TITLE
add missing keys: backslash, numlock, left/right alt

### PR DESCRIPTION
**Pull request by harbdog**

### CODE REVIEW

**Comment by quasilyte** [comment]
I believe you need to run `go generate` to update some mappings as well.

**Comment by harbdog** [comment]
> I believe you need to run `go generate` to update some mappings as well.

done!

**Comment by harbdog** [comment]
@quasilyte any chance this could get merged in soon?

**Comment by quasilyte** [comment]
Yes, sorry. I got distracted.

**Comment by quasilyte** [comment]
Thank you for the PR!

**Pull request merged**
